### PR TITLE
Hooks for plotting images and functions

### PR DESCRIPTION
**Pull request by vdutor**

### CODE REVIEW

**Comment by markvdw** [comment]
Can you add some docstrings? It would be good to know the inputs and outputs of `function` for the save scalar function for instance.

**Comment by markvdw** [comment]
Ok, so the function is without arguments. How does it plot something different for each iteration? Are you referencing variables outside the function's scope? (This seems acceptable for now, I just want to understand usage)

**Comment by vdutor** [comment]
Hi,

I hope this example will illustrate the usage of the `SaveFunction/SaveScalarFunction` and `SaveImage` tasks.

```python
import functools as ft

def plot(model, axes):
    axes = axes.flatten()
    for ax in axes:
        ax.imshow(model.generate_image())

def create_figure():
    return plt.subplots(5, 5, figsize=(10, 10), sharex=True, sharey=True)

def foo(arg1, arg2):
    return arg1 + arg2

model = GPR(...)

task1 = SaveImage(itertools.count(), gpflow_monitor.Trigger.ITER, file_writer,
                lambda fig, axes: plot(model, axes),
                create_figure, "model images", num_channels=3)

task2 = SaveScalarFunction(itertools.count(), gpflow_monitor.Trigger.ITER, 
                           file_writer, ft.partial(foo, 1, 2),  'foo')
```
Instead of `ft.partial` one can also use `lambda` expressions. 

Please let me know if you want more examples or if this isn't clear enough.

**Comment by markvdw** [comment]
Great, but usually when plotting things, you want it to depend on the model. In your actual code, do you just reference the model within the scope of the function, even if it's defined outside the function? (this may be a closure? not sure of the terminology)

**Comment by vdutor** [comment]
In the code snippet above I pass the model as an argument of the `plot` function. Like you are saying, you can also refer to it from within the function even when the model is defined outside the scope.

**Pull request merged**
